<?php

namespace UAHB\ScolariteBundle\Repository;

/**
 * AnneeScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
