<?php

namespace UAHB\ScolariteBundle\Repository;

/**
 * ClasseOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
